import Head from 'next/head'
import Footer from "../components/Footer";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=''>
        <nav className=''>
          <div className=''>About</div>
          <div className=''>Sign in</div>
          <div className=''>Sign up</div>
        </nav>
        <div className=''>
        </div>
      </div>
      <Footer />
    </div>
  )
}
